apiVersion: v1
kind: ResourceQuota

metadata:
  name: wanderlust-quota
  namespace: wanderlust

spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: "1Gi"
    limits.cpu: "4000m"
    limits.memory: "2Gi"
    pods: "10"
    services: "5"

---

apiVersion: v1
kind: LimitRange

metadata:
  name: wanderlust-limit-range

spec:
  limits:
   - max: 
      cpu: "1"
      memory: "350Mi"
   - min:
      cpu: 250m
      memory: "100Mi"
  type: Container